[build.environment]
  NODE_VERSION = "18"

[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  command = "npm run build"
  publish = "dist"

[context.production]
  command = "npm run build"
  publish = "dist"

#[[redirects]]
#  from = "/guide/globals/"
#  to = "/guide/globals/index.html"
#  status = 200

#[[headers]]
#for = "/manifest.webmanifest"
#[headers.values]
#    Content-Type = "application/manifest+json"